/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
    

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require("express");
const app = express();
app.use(express.json());

const myTodos = [
  {
    id: 1,
    title: "Todo 1",
    description: "Description 1",
  },
];

//create a random task id for a new task
// let idCounter = 2;
let currentID = 1;
let idCounterArr = [1];
app.use(express.json());

// 1.GET /todos - Retrieve all todo items
//   Description: Returns a list of all todo items.
//   Response: 200 OK with an array of todo items in JSON format.
//   Example: GET http://localhost:3000/todos

app.get("/todos", async function (req, res) {
  res.status(200).json(myTodos);
});

// 2.GET /todos/:id - Retrieve a specific todo item by ID
// Description: Returns a specific todo item identified by its ID.
// Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
// Example: GET http://localhost:3000/todos/123

app.get("/todos/:id", function (req, res) {
  const id = req.params.id;
  for (let i = 0; i < myTodos.length; i++) {
    if (myTodos[i].id == id) {
      res.status(200).json(myTodos[i]);
    }
  }
  res.status(404).json({
    msg: "Task not found!",
  });
});

// 3. POST /todos - Create a new todo item
//     Description: Creates a new todo item.
//     Request Body: JSON object representing the todo item.
//     Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
//     Example: POST http://localhost:3000/todos
//     Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }

app.post("/todos", function (req, res) {
  const newTask = req.body;

  currentID++; // tracks the To ID for future ref like updating specific todo
  idCounterArr.push(currentID);

  newTask.id = currentID; // Assigning id to new task obj
  // console.log(newTask);
  myTodos.push(newTask); //pushing new task in myTodos

  res.status(201).json({
    msg: `new task added with ID: ${idCounterArr.length}`,
  });
});

// 4. PUT /todos/:id - Update an existing todo item by ID
// Description: Updates an existing todo item identified by its ID.
// Request Body: JSON object representing the updated todo item.
// Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
// Example: PUT http://localhost:3000/todos/123
// Request Body: { "title": "Buy groceries", "completed": true }

//need to test, yet
app.put("/todos/:id", function (req, res) {
  let IdtoUpdate = parseInt(req.params.id);
  console.log(IdtoUpdate);
  console.log(idCounterArr);

  if (!idCounterArr.includes(IdtoUpdate)) {
    res.status(411).json({ msg: "Please provide Valid task ID" });
    return;
  }

  for (let i = 0; i < myTodos.length; i++) {
    if (myTodos[i].id === IdtoUpdate) {
      myTodos[i].title = req.body.title;
      myTodos[i].description = req.body.description;
    }
  }

  res.json({});
});

// 5. DELETE /todos/:id - Delete a todo item by ID
// Description: Deletes a todo item identified by its ID.
// Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
// Example: DELETE http://localhost:3000/todos/123

app.delete("/todos:id", function (req, res) {
  let IdtoDelete = parseInt(req.params.id);
  console.log(IdtoDelete);
  console.log(idCounterArr);

  if (!idCounterArr.includes(IdtoDelete)) {
    res
      .status(404)
      .json({ msg: "Please provide Valid task ID to delete the task" });
    return;
  }

  for (let i = 0; i < myTodos.length; i++) {
    if (myTodos[i].id === IdtoUpdate) {
      ///Logic to delete the toDo task
    }
  }
  res.status(201).json({
    msg: `Task deleted with ID: ${idCounterArr.length}`,
  });
});

app.listen(3000, () => console.log("Server is started"));
